# syntax=docker/dockerfile:1

FROM balenalib/raspberry-pi-debian-python:latest

WORKDIR /app

COPY requirements.txt requirements.txt
RUN python -m venv venv
RUN pip install -r requirements.txt
RUN pip install flask_session

COPY . .

CMD python3 __init__.py
